-- Day 7 Practice

SELECT COUNT(*) FROM EMP;

SELECT SUM(SAL) FROM EMP;

SELECT AVG(SAL) FROM EMP;

SELECT MAX(SAL) FROM EMP;

SELECT MIN(SAL) FROM EMP;

SELECT COUNT(*) FROM EMP WHERE DEPTNO = 20;

SELECT SUM(SAL) FROM EMP WHERE DEPTNO = 30;

SELECT AVG(SAL) FROM EMP WHERE DEPTNO = 10;

SELECT MAX(SAL) FROM EMP WHERE JOB = 'CLERK';

SELECT MIN(SAL) FROM EMP WHERE JOB = 'MANAGER';

SELECT COUNT(*) FROM EMP WHERE SAL > 2000;

SELECT AVG(SAL) FROM EMP WHERE JOB = 'ANALYST';

SELECT MAX(EMPNO) FROM EMP;

SELECT MIN(DEPTNO) FROM EMP;

SELECT MAX(SAL) - MIN(SAL) FROM EMP;
