SELECT ROUND(SAL, 0) FROM EMPLOYEE;

SELECT ENAME, ROUND(SAL, 2) FROM EMPLOYEE;

SELECT CEIL(123.45);

SELECT FLOOR(123.99);

SELECT ABS(-250);

SELECT EMPNO, MOD(EMPNO, 2) FROM EMPLOYEE;

SELECT POWER(5, 2);

SELECT SQRT(144);

SELECT ENAME, SAL, MOD(SAL, 2) FROM EMPLOYEE;

SELECT ENAME, SAL,
CASE
    WHEN SAL >= 3000 THEN 'HIGH'
    WHEN SAL >= 2000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SALARY_LEVEL
FROM EMPLOYEE;

SELECT ENAME, JOB,
CASE
    WHEN JOB = 'MANAGER' THEN 'LEADERSHIP'
    WHEN JOB = 'CLERK' THEN 'SUPPORT'
    ELSE 'OTHER'
END AS JOB_CATEGORY
FROM EMPLOYEE;

SELECT ENAME, SAL,
CASE
    WHEN SAL >= 4000 THEN 'VERY HIGH'
    WHEN SAL >= 3000 THEN 'HIGH'
    WHEN SAL >= 2000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SALARY_LEVEL
FROM EMPLOYEE;

SELECT ENAME, SAL,
CASE
    WHEN SAL >= 3000 THEN 'HIGH'
    WHEN SAL >= 2000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SALARY_LEVEL
FROM EMPLOYEE;

SELECT ENAME, JOB,
CASE
    WHEN JOB = 'MANAGER' THEN 'LEADERSHIP'
    WHEN JOB = 'CLERK' THEN 'SUPPORT'
    ELSE 'OTHER'
END AS JOB_CATEGORY
FROM EMPLOYEE;

SELECT ENAME, EMPNO,
CASE
    WHEN MOD(EMPNO, 2) = 0 THEN 'EVEN'
    ELSE 'ODD'
END AS NUMBER_TYPE
FROM EMPLOYEE;

SELECT ENAME, SAL,
ROUND(SAL, 2) AS ROUNDED_SALARY,
CASE
    WHEN ROUND(SAL, 2) >= 3000 THEN 'HIGH'
    WHEN ROUND(SAL, 2) >= 2000 THEN 'MEDIUM'
    ELSE 'LOW'
END AS SALARY_LEVEL
FROM EMPLOYEE;

SELECT ENAME, SAL,
CASE
    WHEN SAL > 2500 THEN 'ABOVE 2500'
    ELSE '2500 OR BELOW'
END AS SALARY_CATEGORY
FROM EMPLOYEE;

SELECT ENAME, DEPTNO,
CASE
    WHEN DEPTNO = 10 THEN 'DEPT 10'
    WHEN DEPTNO = 20 THEN 'DEPT 20'
    ELSE 'OTHER DEPT'
END AS DEPARTMENT_CATEGORY
FROM EMPLOYEE;

SELECT ENAME, EMPNO,
CASE
    WHEN MOD(EMPNO, 2) = 0 THEN 'EVEN'
    ELSE 'ODD'
END AS NUMBER_TYPE
FROM EMPLOYEE;