-- Day 10 Practice

SELECT DEPTNO, SUM(SAL)
FROM EMPLOYEE
GROUP BY DEPTNO
ORDER BY SUM(SAL);

SELECT DEPTNO, AVG(SAL)
FROM EMPLOYEE
GROUP BY DEPTNO
ORDER BY AVG(SAL) DESC;

SELECT JOB, COUNT()
FROM EMPLOYEE
GROUP BY JOB
ORDER BY COUNT() DESC;

SELECT DEPARTMENT, AVG(SAL)
FROM EMPLOYEE
GROUP BY DEPARTMENT
HAVING AVG(SAL) > 2000
ORDER BY AVG(SAL) DESC;

SELECT DEPARTMENT, JOB, COUNT()
FROM EMPLOYEE
GROUP BY DEPARTMENT, JOB
ORDER BY COUNT() DESC;
