-- Day 12 Practice Queries

-- Q1
SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

-- Q2
SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

-- Q3
SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
FULL JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

-- Q4
SELECT E.ENAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DEPTNO IS NULL;

-- Q5
SELECT D.DNAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IS NULL;

-- Q6
SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

-- Q7
SELECT D.DNAME, E.ENAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

-- Q8
SELECT E.ENAME
FROM EMPLOYEE E
LEFT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DEPTNO IS NULL;

-- Q9
SELECT D.DNAME
FROM EMPLOYEE E
RIGHT JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE E.DEPTNO IS NULL;

-- Q10
SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
FULL JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;
