-- Day 11 Practice

SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

SELECT E.ENAME, E.SAL, D.DNAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO;

SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'HR';

SELECT E.ENAME, D.DNAME
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
WHERE D.DNAME = 'SALES';

SELECT D.DNAME, COUNT(*)
FROM EMPLOYEE E
INNER JOIN DEPARTMENT D
ON E.DEPTNO = D.DEPTNO
GROUP BY D.DNAME;
