SELECT UPPER(ENAME)
FROM EMPLOYEE;

SELECT LOWER(ENAME)
FROM EMPLOYEE;

SELECT ENAME, LENGTH(ENAME)
FROM EMPLOYEE;

SELECT CONCAT(ENAME, JOB)
FROM EMPLOYEE;

SELECT CONCAT(ENAME, ' ', JOB)
FROM EMPLOYEE;

SELECT ENAME, SUBSTRING(ENAME, 1, 3)
FROM EMPLOYEE;

SELECT TRIM('  SQL  ');

SELECT LEFT(ENAME, 3)
FROM EMPLOYEE;

SELECT RIGHT(ENAME, 3)
FROM EMPLOYEE;

SELECT ENAME, UPPER(ENAME)
FROM EMPLOYEE;

SELECT ENAME, LOWER(ENAME)
FROM EMPLOYEE;

SELECT *
FROM EMPLOYEE
WHERE UPPER(JOB) = 'MANAGER';