-- Day 22 Practice SQL
-- Topic: SQL Constraints

-- Q1: Create EMPLOYEE table with PRIMARY KEY
CREATE TABLE EMPLOYEE (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR(50),
SAL DECIMAL(10,2)
);

-- Q2: Create EMPLOYEE table with NOT NULL
CREATE TABLE EMPLOYEE (
EMPNO INT,
ENAME VARCHAR(50) NOT NULL,
SAL DECIMAL(10,2)
);

-- Q3: Create EMPLOYEE table with UNIQUE
CREATE TABLE EMPLOYEE (
EMPNO INT,
ENAME VARCHAR(50),
EMAIL VARCHAR(100) UNIQUE
);

-- Q4: Create DEPARTMENT table
CREATE TABLE DEPARTMENT (
DEPTNO INT PRIMARY KEY,
DNAME VARCHAR(50)
);

-- Create EMPLOYEE table with FOREIGN KEY
CREATE TABLE EMPLOYEE (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR(50),
DEPTNO INT,
FOREIGN KEY (DEPTNO)
REFERENCES DEPARTMENT(DEPTNO)
);

-- Q5: Create EMPLOYEE table with CHECK constraint
CREATE TABLE EMPLOYEE (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR(50),
AGE INT CHECK (AGE >= 18)
);

-- Q6: Create EMPLOYEE table with DEFAULT constraint
CREATE TABLE EMPLOYEE (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR(50),
CITY VARCHAR(30) DEFAULT 'Kolkata'
);

-- Q7: PRIMARY KEY + NOT NULL + UNIQUE
CREATE TABLE EMPLOYEE (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) UNIQUE
);

-- Q8: Table using all constraints
CREATE TABLE EMPLOYEE (
EMPNO INT PRIMARY KEY,
ENAME VARCHAR(50) NOT NULL,
EMAIL VARCHAR(100) UNIQUE,
AGE INT CHECK (AGE >= 18),
CITY VARCHAR(30) DEFAULT 'Kolkata',
DEPTNO INT,
FOREIGN KEY (DEPTNO)
REFERENCES DEPARTMENT(DEPTNO)
);
